In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data_1a=pd.read_csv(r"C:\Users\Gupta\Downloads\exp1a.csv")
data_1b=pd.read_csv(r"C:\Users\Gupta\Downloads\exp1b.csv")
data_1c=pd.read_csv(r"C:\Users\Gupta\Downloads\exp1c.csv")

In [3]:
#Create Y array for the output and X array for the input features
X_1a=data_1a.iloc[:,:-1].values
y_1a=data_1a.iloc[:,-1:].values
X_1b=data_1b.iloc[:,:-1].values
y_1b=data_1b.iloc[:,-1:].values
X_1c=data_1c.iloc[:,:-1].values
y_1c=data_1c.iloc[:,-1:].values

X_data=[X_1a,X_1b,X_1c] #created a list of all the three dataset which contain X features
y_data=[y_1a,y_1b,y_1c] #created a lisr of all the three dataset which conatin Y features

In [13]:
# DecisionTreeClassifier and  LogisticRegression Model
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
clf_t = [DecisionTreeClassifier(criterion='entropy',random_state=0),LogisticRegression()]
names = ['Decision Tree Classifier','Logistic Regression Classifier']

In [19]:
#Modelling
for X,y,name in zip(X_data,y_data,['exp1a','exp1b','exp1c']):
    y=y.ravel()
    print(" The data name is :",name)
    for clf,clf_name in zip(clf_t,names):
        print(" The classifier name is:",clf_name)
        y_pred = cross_val_predict(clf,X,y,cv=10)
        matrix=(confusion_matrix(y, y_pred,labels = [1,-1]))
        score=(cross_val_score(clf, X, y, cv=10))
        print("The confusion matrix of the exp data\n",matrix)
        print("The cross validation score is:\n",score)
        

 The data name is : exp1a
 The classifier name is: Decision Tree Classifier
The confusion matrix of the exp data
 [[198   2]
 [  0 200]]
The cross validation score is:
 [1.    1.    1.    1.    1.    1.    0.975 0.975 1.    1.   ]
 The classifier name is: Logistic Regression Classifier
The confusion matrix of the exp data
 [[110  90]
 [101  99]]
The cross validation score is:
 [0.6   0.6   0.45  0.6   0.525 0.525 0.575 0.35  0.425 0.575]
 The data name is : exp1b
 The classifier name is: Decision Tree Classifier
The confusion matrix of the exp data
 [[ 96   4]
 [  0 200]]
The cross validation score is:
 [1.         1.         0.96666667 1.         1.         1.
 1.         1.         1.         0.9       ]
 The classifier name is: Logistic Regression Classifier
The confusion matrix of the exp data
 [[  0 100]
 [  0 200]]
The cross validation score is:
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667
 0.66666667 0.66666667 0.66666667 0.66666667]
 The data name is : ex